### ISSUE TITLE
Wizard-ify the instance paramters

### ISSUE THREAD

**Issue by jdanish** [theRAPTLab/gsgo#754]
It'd be nice if the instance parameters on the map setup page used a version of the wizard (requiring a popup instead of inline editing is fine).

**Comment by benloh** [comment]
Challenges
* How to differentiate the instance editing from script editing so that they're not confused
* How to provide the appropriate context for instance editing -- e.g. provide visual feedback about the currently selected instance?
* How to manage the wide two-panel (code view / edit view) setup
* Do we open a new window?  Or use a floating dialog?

**Comment by jdanish** [comment]
Will ponder since we have time on this, it appears. Let me know If we need something soon.

**Comment by benloh** [comment]
# Technical Design

Issues

* Instance `initScripts` need to be a part of a blueprint bundle if we want to make use of a wizard.  The blueprint script needs to be compiled and bundled so that the wizard knows which props and features have been defined and are therefore available to be called in the `initScript`.
* The specific script text that is rendered to the`ScriptEditor` is actually coming from `ScriptView_Pane` and `SlotEditor_Block`.  The script text is being passed to `WIZCORE`, and changes in `WIZCORE` state trigger the re-render of `ScriptView_Pane` and `SlotEditor_Block`.  `ScriptEditor` does not directly call `ScriptView_Pane` or `SlotEditor_Block` via props or URSYS network calls (though technically `WIZCORE` state updates are URSYS calls).
*

**Comment by benloh** [comment]
Implemented with #777
